version: "3.7"

services:
  zookeeper:
    image: debezium/zookeeper:1.0
    container_name: zookeeper
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    networks:
      - test
    restart: always

  kafka:
    image: debezium/kafka:1.0
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - test

  kafka-connect:
    image: debezium/connect:1.0
    container_name: kafka-connect
    depends_on:
      - kafka
      - postgres
      - elasticsearch
      - zookeeper
    restart: always
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
      - KEY_CONVERTER=io.confluent.connect.avro.AvroConverter
      - VALUE_CONVERTER=io.confluent.connect.avro.AvroConverter
      - CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL=http://schema-registry:8081
      - CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL=http://schema-registry:8081
      - INTERNAL_KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - INTERNAL_VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
    networks:
      - test

  schema-registry:
    image: confluentinc/cp-schema-registry:5.5.3
    container_name: registry
    environment:
      - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=zookeeper:2181
      - SCHEMA_REGISTRY_HOST_NAME=schema-registry
      - SCHEMA_REGISTRY_LISTENERS=http://schema-registry:8081,http://localhost:8081
      - SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=//kafka:9092

  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=thang
      - POSTGRES_PASSWORD=123
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - test

  elasticsearch:
    image: reborn1998/elasticsearch-vietnamese:1.0.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=datasearch
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      #      - xpack.security.enabled=false
      - xpack.security.enabled=true # enable authentication
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=test
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
      - bootstrap.memory_lock=true
    volumes:
      - ./elasticsearch/data:/var/lib/elasticsearch/data
    ports:
      - "9200:9200"
    depends_on:
      - postgres
      - kafka
      - zookeeper
    networks:
      - test
    restart: always

networks:
  test:
    external: true