version: "3.7"

services:
  redis:
    container_name: redis
    image: redis:6.2-alpine
    networks:
      - test

  pgsync:
    image: reborn1998/pgsync:latest
    labels:
      org.label-schema.name: "pgsync"
      org.label-schema.description: "Postgres to Elasticsearch sync"
      com.label-schema.service-type: "daemon"
    sysctls:
      - net.ipv4.tcp_keepalive_time=200
      - net.ipv4.tcp_keepalive_intvl=200
      - net.ipv4.tcp_keepalive_probes=5
    container_name: pgsync
    depends_on:
      - postgres
      - redis
      - elasticsearch
    environment:
      - PG_USER=postgres
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_PASSWORD=test
      - LOG_LEVEL=INFO
      - ELASTICSEARCH_PORT=9200
      - ELASTICSEARCH_SCHEME=http
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH=true
      - ELASTICSEARCH_USER=elastic
      - ELASTICSEARCH_PASSWORD=test
      - OPENSEARCH=false
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - test

  postgres:
    image: postgres:12.9
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - test

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=datasearch
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      #      - xpack.security.enabled=false
      - xpack.security.enabled=true # enable authentication
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=test
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
      - bootstrap.memory_lock=true
    volumes:
      - ./elasticsearch/data:/var/lib/elasticsearch/data
    ports:
      - "9200:9200"
    depends_on:
      - postgres
      - redis
    networks:
      - test
    restart: always

networks:
  test:
    driver: bridge